# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qernal < Formula
  desc "A CLI tool for Qernal"
  homepage "https://qernal.com/"
  version "0.0.1"
  depends_on :macos

  url "https://github.com/qernal/homebrew-qernal/releases/download/v0.0.1/qernal-cli_0.0.1_darwin_all.zip"
  sha256 "d8c9e1d51bc8329c3190c1fee074ccd816c0ba762dae42f08f441f5df7e5e658"

  def install
    bin.install "qernal-cli"
  end
end
