# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class QernalCli < Formula
  desc "A CLI tool for Qernal"
  homepage "https://qernal.com/"
  version "0.0.2"

  on_macos do
    url "https://github.com/qernal/cli-qernal/releases/download/v0.0.2/qernal-cli_0.0.2_darwin_all.zip"
    sha256 "fa3816e9502371a94add8909b50e68d4643d7d17cc3971bb3a604afaa731f8c8"

    def install
      bin.install "qernal-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/qernal/cli-qernal/releases/download/v0.0.2/qernal-cli_0.0.2_linux_amd64.zip"
        sha256 "76f8968c8bbbd45566cf113f4aeb39dc1abbb44c93718d0b8cb8145e7fb39fd3"

        def install
          bin.install "qernal"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/qernal/cli-qernal/releases/download/v0.0.2/qernal-cli_0.0.2_linux_armv6.zip"
        sha256 "5cd91f330be2db1f09680246c49cef171ef9c40cdf2601538616c0916fdd7a3f"

        def install
          bin.install "qernal"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/qernal/cli-qernal/releases/download/v0.0.2/qernal-cli_0.0.2_linux_arm64.zip"
        sha256 "dae11edc25709dd5a53400ad63db15543e4030982cf24db035b4e6776e5e12ac"

        def install
          bin.install "qernal"
        end
      end
    end
  end
end
